# Imports Used

In [ ]:
import pandas as pd
import tensorflow as tenF
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

# Load Data

In [ ]:
data = pd.read_excel("./Real estate valuation data set.xlsx")

x = data[data.columns[2:-1]].values
y = data[data.columns[-1]].values

# Cat Data

In [ ]:
labe=LabelEncoder()
x[:,2] = labe.fit_transform(x[:,2])

In [ ]:
print(x)

[[ 32.       84.87882  10.       24.98298 121.54024]
 [ 19.5     306.5947    9.       24.98034 121.53951]
 [ 13.3     561.9845    5.       24.98746 121.54391]
 ...
 [ 18.8     390.9696    7.       24.97923 121.53986]
 [  8.1     104.8101    5.       24.96674 121.54067]
 [  6.5      90.45606   9.       24.97433 121.5431 ]]


# Split it

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

# Feature Scaling

In [ ]:
stdSC = StandardScaler()
x_train = stdSC.fit_transform(x_train)
x_test = stdSC.transform(x_test)

# Neural  Net Part

In [ ]:
neuN=tenF.keras.models.Sequential()

In [ ]:
neuN.add(tenF.keras.layers.Dense(units=6,activation = 'relu'))

In [ ]:
neuN.add(tenF.keras.layers.Dense(units=7,activation = 'relu'))

In [ ]:
neuN.add(tenF.keras.layers.Dense(units=1,activation = 'softmax'))

In [ ]:
neuN.compile(optimizer = 'adam',loss='binary_crossentropy',metrics = ['accuracy'])

In [ ]:
neuN.fit(x_train,y_train,epochs = 100,batch_size = 32)

Epoch 1/100
10/10 [==============================] - 1s 2ms/step - loss: 5.7895 - accuracy: 0.0000e+00
Epoch 2/100
10/10 [==============================] - 0s 3ms/step - loss: 3.2523 - accuracy: 0.0000e+00
Epoch 3/100
10/10 [==============================] - 0s 3ms/step - loss: 0.7189 - accuracy: 0.0000e+00
Epoch 4/100
10/10 [==============================] - 0s 3ms/step - loss: -1.8101 - accuracy: 0.0000e+00
Epoch 5/100
10/10 [==============================] - 0s 2ms/step - loss: -4.5282 - accuracy: 0.0000e+00
Epoch 6/100
10/10 [==============================] - 0s 2ms/step - loss: -7.3466 - accuracy: 0.0000e+00
Epoch 7/100
10/10 [==============================] - 0s 2ms/step - loss: -10.3569 - accuracy: 0.0000e+00
Epoch 8/100
10/10 [==============================] - 0s 3ms/step - loss: -13.6288 - accuracy: 0.0000e+00
Epoch 9/100
10/10 [==============================] - 0s 2ms/step - loss: -17.3885 - accuracy: 0.0000e+00
Epoch 10/100
10/10 [==============================] - 0s 2ms/ste

# Predict

In [ ]:
neuN.predict(stdSC.transform([[32,84.87882,5,24.96305,121.51726]]))

1/1 [==============================] - 0s 59ms/step


array([[1.]], dtype=float32)

In [ ]:
y_pred = neuN.predict(x_test)
y_pred = (y_pred >0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

4/4 [==============================] - 0s 3ms/step
[[ 1.  45.3]
 [ 1.  14.4]
 [ 1.  46. ]
 [ 1.  15.6]
 [ 1.  50.2]
 [ 1.  38.1]
 [ 1.  48.5]
 [ 1.  41.4]
 [ 1.  51.6]
 [ 1.  40.1]
 [ 1.  42. ]
 [ 1.  42.4]
 [ 1.  28.5]
 [ 1.  39.1]
 [ 1.  53.7]
 [ 1.  36.8]
 [ 1.  40.6]
 [ 1.  55.2]
 [ 1.  39.3]
 [ 1.  44.3]
 [ 1.  53.5]
 [ 1.  25.3]
 [ 1.  22.8]
 [ 1.  51.7]
 [ 1.  45.5]
 [ 1.  34.4]
 [ 1.  31.6]
 [ 1.  25.9]
 [ 1.  49.5]
 [ 1.  24.7]
 [ 1.  51.7]
 [ 1.  29.7]
 [ 1.  45.4]
 [ 1.  50.5]
 [ 1.  26.5]
 [ 1.  30.1]
 [ 1.  46.1]
 [ 1.  28.9]
 [ 1.  54.4]
 [ 1.  15. ]
 [ 1.  44.9]
 [ 1.  29.8]
 [ 1.  23.6]
 [ 1.  48. ]
 [ 1.  16.7]
 [ 1.  40.9]
 [ 1.  40.2]
 [ 1.  12.9]
 [ 1.  21.3]
 [ 1.  62.1]
 [ 1.  63.9]
 [ 1.  40.3]
 [ 1.  42.2]
 [ 1.  19.1]
 [ 1.  28.4]
 [ 1.  28.5]
 [ 1.  60.7]
 [ 1.  37.5]
 [ 1.  39.3]
 [ 1.  28.8]
 [ 1.  42.3]
 [ 1.  44.3]
 [ 1.  42.6]
 [ 1.  57.4]
 [ 1.  42.2]
 [ 1.  25.7]
 [ 1.  13.2]
 [ 1.  27. ]
 [ 1.  56.2]
 [ 1.  38.3]
 [ 1.  20.8]
 [ 1.  43.1]
 [ 1.  78.3]


In [ ]:
print(y_test,y_pred)

[45.3 14.4 46.  15.6 50.2 38.1 48.5 41.4 51.6 40.1 42.  42.4 28.5 39.1
 53.7 36.8 40.6 55.2 39.3 44.3 53.5 25.3 22.8 51.7 45.5 34.4 31.6 25.9
 49.5 24.7 51.7 29.7 45.4 50.5 26.5 30.1 46.1 28.9 54.4 15.  44.9 29.8
 23.6 48.  16.7 40.9 40.2 12.9 21.3 62.1 63.9 40.3 42.2 19.1 28.4 28.5
 60.7 37.5 39.3 28.8 42.3 44.3 42.6 57.4 42.2 25.7 13.2 27.  56.2 38.3
 20.8 43.1 78.3 20.9 32.5 33.4 32.1 19.2 53.  38.2 46.7 24.6 36.2 23.2
 29.3 38.4 37.5 34.3 44.8 54.4 37.9  7.6 29.5 25.3 13.7 30.  30.8 40.6
 20.7 40.8 55.3 40.5 40.8 40.3] [[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ 

In [ ]:
confMatrix = confusion_matrix(y_test, y_pred)

print(confMatrix)

ValueError: ignored