Neutral Network

In [1]:
import pandas as pd

dataset= pd.read_csv("Real estate valuation data set.csv")


X= dataset[dataset.columns[2:-1]].values
y= dataset[dataset.columns[-1]].values



# print(X)



Categorical data

In [2]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,1])



In [3]:
print(X)

[[ 32.       84.87882   5.       24.98298 121.54024]
 [ 19.5     306.5947   59.       24.98034 121.53951]
 [ 13.3     561.9845  134.       24.98746 121.54391]
 ...
 [ 18.8     390.9696   91.       24.97923 121.53986]
 [  8.1     104.8101    8.       24.96674 121.54067]
 [  6.5      90.45606   7.       24.97433 121.5431 ]]


Split

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

Neural Network

In [6]:
#init ANN
import tensorflow as tf
ann=tf.keras.models.Sequential()


In [7]:
#adding hidden layers
ann.add(tf.keras.layers.Dense(units=6,activation='softplus'))
ann.add(tf.keras.layers.Dense(units=8,activation='softplus' ))
ann.add(tf.keras.layers.Dense(units=10,activation='softplus'))
ann.add(tf.keras.layers.Dense(units=12,activation='softplus'))

In [9]:
#output layer

ann.add(tf.keras.layers.Dense(units=1,activation='linear'))

In [10]:
#compiling ANN
ann.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

In [11]:
#training ANN

ann.fit(X_train,y_train,epochs=100,batch_size=32)


Epoch 1/100
11/11 [==============================] - 0s 801us/step - loss: 1587.7977 - accuracy: 0.0000e+00
Epoch 2/100
11/11 [==============================] - 0s 701us/step - loss: 1566.9794 - accuracy: 0.0000e+00
Epoch 3/100
11/11 [==============================] - 0s 801us/step - loss: 1544.4949 - accuracy: 0.0000e+00
Epoch 4/100
11/11 [==============================] - 0s 701us/step - loss: 1519.8007 - accuracy: 0.0000e+00
Epoch 5/100
11/11 [==============================] - 0s 801us/step - loss: 1492.3564 - accuracy: 0.0000e+00
Epoch 6/100
11/11 [==============================] - 0s 701us/step - loss: 1460.3998 - accuracy: 0.0000e+00
Epoch 7/100
11/11 [==============================] - 0s 652us/step - loss: 1422.8611 - accuracy: 0.0000e+00
Epoch 8/100
11/11 [==============================] - 0s 752us/step - loss: 1377.6118 - accuracy: 0.0000e+00
Epoch 9/100
11/11 [==============================] - 0s 752us/step - loss: 1323.2427 - accuracy: 0.0000e+00
Epoch 10/100
11/11 [========

In [12]:
#predict
ann.predict(sc.transform([[32,84.87882,10,24.98298,121.54024]]))


1/1 [==============================] - 0s 52ms/step


array([[52.36837]], dtype=float32)

In [15]:
#Mean Error

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = ann.predict(X_test)
r2 = r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
print("Mean Absolute Error: ",mae)
print("Mean Square Error: ",mse)
print("R Square Error: ",r2)
print(y_pred)

3/3 [==============================] - 0s 1ms/step
Mean Absolute Error:  4.931774176172463
Mean Square Error:  44.80554951059762
R Square Error:  0.7420506382989422
[[45.362087]
 [18.48157 ]
 [43.77957 ]
 [18.417625]
 [45.895645]
 [36.73877 ]
 [42.89972 ]
 [37.0223  ]
 [50.59317 ]
 [44.857613]
 [44.401962]
 [34.70179 ]
 [45.413277]
 [42.805817]
 [54.434967]
 [36.285538]
 [36.12261 ]
 [50.703125]
 [34.687046]
 [46.929405]
 [57.803944]
 [28.33239 ]
 [38.48798 ]
 [51.101738]
 [48.70842 ]
 [40.601173]
 [38.464447]
 [25.066889]
 [49.573124]
 [30.11689 ]
 [39.738476]
 [32.09534 ]
 [49.64998 ]
 [40.499535]
 [38.58487 ]
 [28.28078 ]
 [51.574043]
 [30.844095]
 [50.055893]
 [19.920568]
 [49.002094]
 [36.15856 ]
 [27.74178 ]
 [51.97391 ]
 [19.215467]
 [35.182487]
 [38.405384]
 [19.32134 ]
 [25.6905  ]
 [46.35829 ]
 [57.403175]
 [36.544437]
 [47.22132 ]
 [23.630327]
 [28.358458]
 [35.485207]
 [52.184853]
 [37.03377 ]
 [44.546684]
 [32.17049 ]
 [36.829815]
 [48.911316]
 [37.3326  ]
 [50.85617 ]
 [4